Vagrant.configure("2") do |config|

  #It is necessary to install the Landrush plugin - form the directory where the vagrantfile is located
  #run vagrant plugin install landrush - ref. https://github.com/vagrant-landrush/landrush 

  # config.vm.define "dns" do |dns|
  # config.landrush.enabled = true  
  #   dns.vm.box = "hashicorp/precise64"
  #   dns.vm.hostname = "dns.kimikilab.com"
  #   dns.vm.network "private_network", ip: "192.168.33.5"
  # end
  
  config.vm.define "acs" do |acs|
  config.landrush.enabled = true  
    acs.vm.box = "ubuntu/xenial64"
    acs.vm.hostname = "acs.kimikilab.com"
    acs.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "web" do |web|
  config.landrush.enabled = true
    web.vm.box = "centos/7"
    web.vm.hostname = "web.kimikilab.com"
    web.vm.network "private_network", ip: "192.168.33.20"
    web.vm.network "forwarded_port", guest: 80, host: 8080
  end

  # config.vm.define "db" do |db|
  #   db.vm.box = "centos/7"
  #   db.vm.hostname = "db.kimikilab.com"
  #   db.vm.network "private_network", ip: "192.168.33.30"
  #   #db.vm.network "forwarded_port", guest: 80, host: 8080
  # end

  config.vm.define "gitlab" do |gitlab|
  config.landrush.enabled = true
    gitlab.vm.box = "ubuntu/xenial64"
    gitlab.vm.hostname = "gitlab.kimikilab.com"
    gitlab.vm.network "private_network", ip: "192.168.33.40"
    gitlab.vm.network "forwarded_port", guest: 80, host: 8085
    gitlab.vm.network "forwarded_port", guest: 443, host: 8443
    gitlab.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end



  # config.vm.define "tower" do |tower|
  #   tower.vm.box = "centos/7"
  #   tower.vm.hostname = "tower.kimikilab.com"
  #   tower.vm.network "private_network", ip: "192.168.33.60"
  #   tower.vm.network "forwarded_port", guest: 80, host: 8090
  #   tower.vm.network "forwarded_port", guest: 443, host: 8445
  #   tower.vm.provider "virtualbox" do |v|
  #     v.memory = 2048
  #   end    
  # end

  # config.vm.define "win12" do |win12|
  #   win12.vm.box = "mwrock/Windows2012R2"
  #   config.landrush.enabled = false
  #   win12.vm.hostname = "win12"
  #   win12.vm.communicator = "winrm"
  #   # win12.vm.username = "vagrant"
  #   # win12.vm.password = "vagrant"
  #   win12.vm.network "private_network", ip: "192.168.33.50"
  #   win12.vm.network "forwarded_port", guest: 80, host: 8086
  #   #win12.vm.network "forwarded_port", guest: 443, host: 8444
  #   win12.vm.provider "virtualbox" do |v|
  #     v.memory = 2048
  #     # v.cpus = 2
  #   end  
  # end

  # config.vm.define "win12bis" do |win12bis|
  #   win12bis.vm.box = "jptoto/Windows2012R2"
  #   config.landrush.enabled = false
  #   win12bis.vm.hostname = "win12"
  #   win12bis.vm.communicator = "winrm"
  #   # win12bis.vm.username = "vagrant"
  #   # win12bis.vm.password = "vagrant"
  #   win12bis.vm.network "private_network", ip: "192.168.33.70"
  #   win12bis.vm.network "forwarded_port", guest: 80, host: 8087
  #   #win12bis.vm.network "forwarded_port", guest: 443, host: 8444
  #   win12bis.vm.provider "virtualbox" do |v|
  #     v.memory = 2048
  #     # v.cpus = 2
  #   end  
  # end



  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end